<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogues [
	<!ELEMENT dialogues ANY>
	<!ELEMENT dialogue ANY>
	<!ELEMENT text ANY>
	<!ELEMENT options ANY>
	<!ELEMENT option ANY>
	<!ELEMENT goto ANY>
	<!ATTLIST dialogue name ID #REQUIRED>
]>
<dialogues>
	<dialogue name='_0'>
		<text>This is the first line of dialogue. What do you think of it? (To stop talking, just walk away!)</text>
		<options>
			<option>
				<text>It's all right?</text>
				<goto>_1</goto>
			</option>
			<option>
				<text>It sucks!</text>
				<goto>_2</goto>
			</option>
		</options>
	</dialogue>
	<dialogue name='_1'>
		<text>Why thank you!</text>
		<options>
			<option>
				<text>Uh, you're welcome, I guess? (go back)</text>
				<goto>_0</goto>
			</option>
		</options>
	</dialogue>
	<dialogue name='_2'>
		<text>Screw you man you have no idea how hard i worked on this shit man i am tired of just getting criticized all the dam time</text>
		<options>
			<option>
				<text>:^( (go back)</text>
				<goto>_0</goto>
			</option>
		</options>
	</dialogue>
</dialogues>